/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Aboutus`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/About` | `/About`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/Home3` | `/home/Home3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/Home2` | `/home/Home2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/Home4` | `/home/Home4`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/user/[id]` | `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Aboutus`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/About` | `/About`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home/Home3` | `/home/Home3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home/Home2` | `/home/Home2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home/Home4` | `/home/Home4`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/user/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}/user/[id]` | `/user/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/Aboutus${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/About${`?${string}` | `#${string}` | ''}` | `/About${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home/Home3${`?${string}` | `#${string}` | ''}` | `/home/Home3${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home/Home2${`?${string}` | `#${string}` | ''}` | `/home/Home2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home/Home4${`?${string}` | `#${string}` | ''}` | `/home/Home4${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Aboutus`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/About` | `/About`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/Home3` | `/home/Home3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/Home2` | `/home/Home2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/Home4` | `/home/Home4`; params?: Router.UnknownInputParams; } | `/+not-found` | `/user/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/user/${Router.SingleRoutePart<T>}` | `/user/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/user/[id]` | `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
